### PR TITLE
Broker's Ingress RabbitMQ Channel and Connection recovery

### LINKED ISSUE #534: Broker ingress does not reconnect if connection to the RMQ is lost
**Describe the bug**
If for some reason the ingresses' connection to the RabbitMQ server is lost, it will go into a permanent failure loop.

 **Expected behavior**
It should either exit on failure and allow k8s to restart it or re-establish the connection.

 **To Reproduce**
- Deploy a broker/trigger topology ([for example](https://gist.github.com/benmoss/a32017ec40eb22c53191c462c5d3f2db))
- Determine the ingress pods IP via `kubectl get pods -o wide`
- Go into the RMQ management dashboard, go to the "Connections" tab, select the connection with the matching IP, and manually close the connection via "Force Close" at the bottom:
Force close connection
- Observe that the ingress goes into a failure loop, with a particularly [unhelpful error message](https://github.com/knative-sandbox/eventing-rabbitmq/blob/4cf1cf0762a981a23813b3170a48ff538df32776/cmd/ingress/main.go#L147). We should log the RabbitMQ `err` here for better troubleshooting in the future.

 **Knative release version**
Deployed from main branch

 **Additional context**
This is the error it'll continually log:
```json
{"level":"error","ts":1638542285.9604282,"logger":"fallback","caller":"ingress/main.go:119","msg":"failed to send event,failed to publish message","stacktrace":"main.(*envConfig).ServeHTTP\n\tknative.dev/eventing-rabbitmq/cmd/ingress/main.go:119\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\tgo.opencensus.io@v0.23.0/plugin/ochttp/server.go:92\nknative.dev/pkg/network/handlers.(*Drainer).ServeHTTP\n\tknative.dev/pkg@v0.0.0-20211101212339-96c0204a70dc/network/handlers/drain.go:104\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2878\nnet/http.(*conn).serve\n\tnet/http/server.go:1929"
```

### PR DESCRIPTION
**Pull request by gabo1208**
# Changes

-  :gift: Added reconnection for RabbitMQ channels

/kind enhancement

Fixes #534

**Release Note**

```release-note
Now the RabbitMQ's Broker Ingress pod can recover from a closed Channel or Connection
```

### CODE REVIEW

**Comment by gabo1208** [comment]
/hold
 Going to do some specific tests

File: pkg/rabbit/setup.go [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+	if channel, err = connection.Channel(); err != nil {
+		logger.Fatalw("Failed to open a channel", zap.Error(err))
+	}
+
+	// noWait is false
+	if err = channel.Confirm(false); err != nil {
+		logger.Fatalf("Failed to switch connection channel to confirm mode: %s", err)
+	}
+
+	if err != nil {
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:56]: this block may be some stale code? we have the go routine to attempt another reconnect. and the retryNumber += 0 doesn't do anything

File: pkg/rabbit/setup.go [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+const maxRetries = 5
+
+func SetupRabbitMQ(
+	connection wabbit.Conn,
+	channel wabbit.Channel,
+	brokerURL string,
+	retryNumber *int,
+	logger *zap.SugaredLogger) {
+	if *retryNumber >= maxRetries {
+		logger.Fatalf("Max retries (%d) reached, unable to setup RabbitMQ correctly", maxRetries)
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:34]: Once we reach maxRetries, we're failing the pod and then letting k8s handle re-running the pod with a backoff? I think that's fine, just confirming that's what we want.

File: pkg/rabbit/setup.go (hunk 1 above)
Comment (gabo1208) [reply pkg/rabbit/setup.go:56]: My bad that i left += 0 but this code makes sense im commenting for it to be clearer. Ill push after the tests are ready :)

File: pkg/rabbit/setup.go (hunk 2 above)
Comment (gabo1208) [reply pkg/rabbit/setup.go:34]: That's exactly what I'm aiming for, the next push should behave like that

**Comment by gabo1208** [comment]
This is the codecov error too, so this is ready to be reviewed and merged :)

File: cmd/ingress/main.go [hunk 3]
```diff
@@ -49,68 +51,73 @@ type envConfig struct {
...
 func main() {
 	ctx := signals.NewContext()
-
 	var env envConfig
 	if err := envconfig.Process("", &env); err != nil {
 		logging.FromContext(ctx).Fatal("Failed to process env var: ", err)
 	}
 
 	env.SetComponent(component)
+	var err error
```
Comment (gab-satchi) [inline cmd/ingress/main.go:66]: nit: just have `if err := env...` in line 70

File: cmd/ingress/main.go [hunk 4]
```diff
@@ -49,68 +51,73 @@ type envConfig struct {
...
 	}
 
+	retryChannel := make(chan bool)
+	env.CreateRabbitMQResources(retryChannel, logger)
 	// noWait is false
-	if err := env.channel.Confirm(false); err != nil {
-		logger.Fatalf("faild to switch connection channel to confirm mode: %s", err)
-	}
-	defer env.channel.Close()
+	if err = env.channel.Confirm(false); err != nil {
```
Comment (gab-satchi) [inline cmd/ingress/main.go:81]: if there's an error during `env.CreateRabbitMQResources`, it's quietly ignored and env.channel is unset. that would cause a nil pointer exception here

File: cmd/ingress/main.go [hunk 5]
```diff
@@ -49,68 +51,73 @@ type envConfig struct {
...
 
-	env.channel, err = conn.Channel()
-	if err != nil {
-		logger.Fatalw("failed to open a channel", zap.Error(err))
+	if err = env.SetupMetrics(ctx); err != nil {
+		logger.Errorw("Failed to create the metrics exporter", zap.Error(err))
 	}
 
+	retryChannel := make(chan bool)
+	env.CreateRabbitMQResources(retryChannel, logger)
```
Comment (gab-satchi) [inline cmd/ingress/main.go:79]: nit: `CreateRabbitMQResources` is a bit vague. We're setting up the connection and channel. Resources feels really broad

File: pkg/rabbit/setup.go [hunk 6]
```diff
@@ -0,0 +1,132 @@
...
+	cleaningUp                                          = false
+	DialFunc          func(string) (wabbit.Conn, error) = wabbitamqp.Dial
+)
+
+func SetDialFunc(dialFunc func(uri string) (wabbit.Conn, error)) {
+	DialFunc = dialFunc
+}
+
+func SetupRabbitMQ(
+	brokerURL string,
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:46]: nit: brokerURL is confusing here since we have a different brokerURL that's basically the ingress service URL. Maybe RabbitMQURL or ServerURL

File: pkg/rabbit/setup.go [hunk 7]
```diff
@@ -0,0 +1,132 @@
...
+		cycleNumber += 1
+		retryCounter = 0
+		if cycleDuration == 1 {
+			cycleDuration += 1
+		} else if cycleDuration < maxCycleDuration {
+			cycleDuration *= cycleDuration
+		} else if cycleDuration > maxCycleDuration {
+			cycleDuration = maxCycleDuration
+		}
+		logger.Warnf("Max retries (%d) reached for a cycle, adjusting duration to %ss", cycleRetries, cycleDuration)
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:60]: nit: should it read: `adjusting duration to %s ms`?

File: pkg/rabbit/setup.go [hunk 8]
```diff
@@ -0,0 +1,132 @@
...
+
+func SetupRabbitMQ(
+	brokerURL string,
+	retryChannel chan<- bool,
+	logger *zap.SugaredLogger) (wabbit.Conn, wabbit.Channel, error) {
+	// Calculate the current cycle time to sleep in ms
+	if retryCounter >= cycleRetries {
+		cycleNumber += 1
+		retryCounter = 0
+		if cycleDuration == 1 {
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:53]: I think the edgecase of having cycleDuration set to 1 is overcomplicating things. If we just want an exponential backoff, can we just start at 2?

File: pkg/rabbit/setup.go [hunk 9]
```diff
@@ -0,0 +1,132 @@
...
+	var channel wabbit.Channel
+	if conn, err = DialFunc(brokerURL); err != nil {
+		logger.Errorw("Failed to connect to RabbitMQ", zap.Error(err))
+	} else if channel, err = conn.Channel(); err != nil {
+		logger.Errorw("Failed to open a channel", zap.Error(err))
+	}
+
+	// If there is an error trying to setup rabbit, and the Retrying is true retry
+	if err != nil && Retrying {
+		if cycleDuration <= 0 {
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:75]: is this ever a possibility?

File: pkg/rabbit/setup.go [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+			return nil, nil, errors.New("InitCycleDuration needs to be a positive integer")
+		}
+
+		time.Sleep(time.Millisecond * time.Duration(cycleDuration*(retryCounter)-1))
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:79]: not sure if the -1 was meant to be inside of the parentheses so it's like cycleDuration * (retryCounter -1)

File: pkg/rabbit/setup.go [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+		return SetupRabbitMQ(brokerURL, retryChannel, logger)
+	} else if err != nil && !Retrying {
+		return nil, nil, err
+	}
+	// if Retrying is true and error nil reset the retryCounter and cycle values
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:84]: When is Retrying (the bool) set to false?

File: pkg/rabbit/setup.go (hunk 7 above)
Comment (gabo1208) [reply pkg/rabbit/setup.go:60]: In this case I'm using seconds

File: pkg/rabbit/setup.go (hunk 8 above)
Comment (gabo1208) [reply pkg/rabbit/setup.go:53]: The thing is if the error is just a simple fail, waiting two seconds could bee too much

File: pkg/rabbit/setup.go (hunk 9 above)
Comment (gabo1208) [reply pkg/rabbit/setup.go:75]: Just in the tests, I'll remove it

File: pkg/rabbit/setup.go (hunk 11 above)
Comment (gabo1208) [reply pkg/rabbit/setup.go:84]: in the tests, and i was planning that it could be a user toggle. But right now I'll leave it private and see if it comes handy at any point apart from testing if that's ok

File: pkg/rabbit/setup.go [hunk 12]
```diff
@@ -0,0 +1,127 @@
...
+	var channel wabbit.Channel
+	if conn, err = DialFunc(brokerURL); err != nil {
+		logger.Errorw("Failed to connect to RabbitMQ", zap.Error(err))
+	} else if channel, err = conn.Channel(); err != nil {
+		logger.Errorw("Failed to open a channel", zap.Error(err))
+	}
+
+	// If there is an error trying to setup rabbit, and the retrying is true retry
+	if err != nil && retrying {
+		time.Sleep(time.Millisecond * time.Duration(cycleDuration*retryCounter))
```
[the remark this answers is not in the document]
Comment (gabo1208) [reply pkg/rabbit/setup.go:74]: Changed to seconds and maxed to 60. Seen it now it seems a bit much the 7600 🙃

File: pkg/rabbit/setup.go [hunk 13]
```diff
@@ -0,0 +1,127 @@
...
+
+func SetDialFunc(dialFunc func(uri string) (wabbit.Conn, error)) {
+	DialFunc = dialFunc
+}
+
+func SetupRabbitMQ(
+	RabbitMQURL string,
+	retryChannel chan<- bool,
+	logger *zap.SugaredLogger) (wabbit.Conn, wabbit.Channel, error) {
+	// Calculate the current cycle time to sleep in ms
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:48]: maybe change this comment to be seconds

File: pkg/rabbit/setup.go (hunk 11 above)
Comment (gab-satchi) [reply pkg/rabbit/setup.go]: I don't think we want to introduce fields that are only there for testing purposes. It's usually a smell that either the tests are structured wrong or the components design may need changing

**Comment by gab-satchi** [comment]
I think backoff is good to have. So we're not bring down the server with connection attempts. A variable backoff is what I'm seeing as overkill. A 1 second wait before re-attempts will be sufficient not to bring the server down.

File: pkg/rabbit/setup.go [hunk 14]
```diff
@@ -0,0 +1,105 @@
...
+
+	// If there is an error trying to setup rabbit send a retry msg
+	if err != nil {
+		time.Sleep(time.Second * time.Duration(cycleDuration))
+		retryChannel <- true
+		return nil, nil, err
+	}
+
+	// if there is no error reset the retryCounter and cycle values
+	retryCounter = 0
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:60]: do we need a retryCounter anymore?

File: pkg/rabbit/setup.go [hunk 15]
```diff
@@ -0,0 +1,105 @@
...
+	"time"
+
+	"github.com/NeowayLabs/wabbit"
+	wabbitamqp "github.com/NeowayLabs/wabbit/amqp"
+	"go.uber.org/zap"
+)
+
+var (
+	retryCounter                                    = 0
+	cycleDuration                                   = 2
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:29]: maybe make cycleDuration a time.Duration of 2 seconds

File: pkg/rabbit/setup.go [hunk 16]
```diff
@@ -0,0 +1,105 @@
...
+	cleaningUp                                      = false
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:30]: If the plan is to reuse this package, we can't have a global variables like this

File: pkg/rabbit/setup.go (hunk 14 above)
Comment (gabo1208) [reply pkg/rabbit/setup.go:60]: For loggin purposes

File: pkg/rabbit/setup.go (hunk 16 above)
Comment (gabo1208) [reply pkg/rabbit/setup.go:30]: hmmm they are private but what do you suggest?

Comment (gab-satchi) [reply pkg/rabbit/setup.go]: It's more like if you have A and B using this service simultaneously, they'll both be clobbering each others states. Was suggesting to move them into a struct but looks like you just did that 👍

File: cmd/ingress/main.go [hunk 17]
```diff
@@ -122,15 +139,15 @@ func (env *envConfig) ServeHTTP(writer http.ResponseWriter, request *http.Reques
 
 	event, err := binding.ToEvent(ctx, message)
 	if err != nil {
-		logger.Warnw("failed to extract event from request", zap.Error(err))
```
Comment (gab-satchi) [inline cmd/ingress/main.go:125]: nit: the errors/msgs should be lower case. It's the go convention

File: cmd/ingress/main.go [hunk 18]
```diff
@@ -182,5 +201,21 @@ func (env *envConfig) send(event *cloudevents.Event, span *trace.Span) (int, err
...
+	rmqHelper *rabbit.RabbitMQHelper,
+	retryChannel chan<- bool,
+	logger *zap.SugaredLogger) (wabbit.Conn, wabbit.Channel, error) {
+	conn, channel, err := rmqHelper.SetupRabbitMQ(env.BrokerURL, retryChannel, logger)
+	if err != nil {
+		return nil, nil, err
+	}
+
+	if err := env.channel.Confirm(false); err != nil {
+		logger.Errorw("Failed to switch connection channel to confirm mode: %s", zap.Error(err))
```
Comment (gab-satchi) [inline cmd/ingress/main.go:218]: It seems we used to do a `Fatalf` and fail the pod in this error case but now it's getting silently ignored.

File: pkg/rabbit/setup.go [hunk 19]
```diff
@@ -0,0 +1,113 @@
...
+	retryChannel chan<- bool,
+	logger *zap.SugaredLogger) {
+	var err error
+	select {
+	case err = <-connection.NotifyClose(make(chan wabbit.Error)):
+	case err = <-channel.NotifyClose(make(chan wabbit.Error)):
+	}
+	if !r.cleaningUp {
+		logger.Warn(
+			"Lost connection to RabbitMQ, reconnecting retry number %d. Error: %v",
```
Comment (gab-satchi) [inline pkg/rabbit/setup.go:87]: I see the retryNumber getting used here, but wouldn't it always be 0? Since to get to this spot of receiving a closed notification, we'd need a successful connection/channel at which point we reset the retry count to 0 on L68. Maybe retryCount makes more sense in the errors in L55 and L57

**Review by gab-satchi — COMMENTED** [review]
minor comments

File: cmd/ingress/main.go (hunk 17 above)
Comment (gab-satchi) [reply cmd/ingress/main.go:125]: Capitalization here should be fine since we're printing things. disregard

**Comment by gab-satchi** [comment]
Thanks @gabo1208 for the changes. Let's get another set of eyes on it cc: @ChunyiLyu @ikvmw

**Review by ChunyiLyu — APPROVED** [review]
LGTM

**Review by gab-satchi — APPROVED** [review]
Thanks for the changes @gabo1208 

/lgtm
