### PR TITLE
Wabbit removal with tests

### LINKED ISSUE #647: Add RabbitMQ Channels and Connections reconnection for all the CRDs
**Problem**
When there is a problem with a RabbitMQ's Channel or Connection that make any of them close, the CRD then is unable to communicate with the RabbitMQ's resources.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
All

**Exit Criteria**

- [x] Broker Ingress reconnects when its RabbitMQ Channel or Connection is closed (#534) PR #648
- [ ] Broker Dispatcher reconnects when its RabbitMQ Channel or Connection is closed PR #649
- [ ] Source Receive adapter reconnects when its RabbitMQ Channel or Connection is closed PR #650
- [ ] This implies a refactor to remove wabbit, start using the amqp-go client and mock it for testing

**Additional context (optional)**
To reproduce, create a Broker or a Source, go to the RabbitMQ's management UI, identify any Channel associated with the Broker or Source, close it and start sending messages.

### PR DESCRIPTION
**Pull request by gabo1208**
# Changes

- 🎁 Now the Ingres, Dispatcher and Receive Adapter pods reconnects gracefully after a RabbitMQ connection error
-  🧹 Removed wabbit pkg (a helper pkg for the RabbitMQ bits that is no longer maintained), replaced with mocks and tests
-  🧹 Removed e2e tests from the unit test section of the Dispatcher and Receive adapter

/kind removal, enhancement

Fixes #647 

**Release Note**

```release-note
🎁 Ingres, Dispatcher and Receive Adapter pods reconnects gracefully after a RabbitMQ connection error
```

### CODE REVIEW

File: cmd/dispatcher/main.go [hunk 1]
```diff
@@ -58,16 +56,16 @@ type envConfig struct {
...
+	channel    rabbit.RabbitMQChannelInterface
 }
 
 func main() {
 	ctx := signals.NewContext()
 
 	// Report stats on Go memory usage every 30 seconds.
 	metrics.MemStatsOrDie(ctx)
-
+	var err error
```
Comment (gab-satchi) [inline cmd/dispatcher/main.go:68]: nit: move this down to the for loop where it's relevant

File: cmd/ingress/main.go [hunk 2]
```diff
@@ -92,26 +92,22 @@ func main() {
 		logger.Errorw("failed to create the metrics exporter", zap.Error(err))
 	}
 
-	rmqHelper := rabbit.NewRabbitMQHelper(1, make(chan bool))
+	rmqHelper := rabbit.NewRabbitMQHelper(1, make(chan bool), rabbit.DialWrapper)
 	// Wait for RabbitMQ retry messages
+	defer rmqHelper.CleanupRabbitMQ(env.connection, logger)
 	go func() {
```
Comment (gab-satchi) [inline cmd/ingress/main.go:98]: The connection/channel is initialized async along with the HttpServer that would receive events. Should we be protecting against a NPE at around L200? We don't check that the channel exists before attempting to send the event out.

**Review by gab-satchi — COMMENTED** [review]
just some minor things

**Review by gab-satchi — APPROVED** [review]
/lgtm
