### PR TITLE
replaced knative eventing heartbeats location in hack/tools go script imports

### LINKED ISSUE #1107: Change removed image with actual one
**Describe the bug**

`heartbeats` test image was removed, and needs to be replaced, like:
https://github.com/knative-sandbox/eventing-ceph/pull/330/files#diff-c70c0ccc1e4ba2d6da1d6c59877e3600c6771f133dec670df485e23fde6cb795

### PR DESCRIPTION
**Pull request by gabo1208**
# Changes

- 🧹 replaced knative eventing heartbeats location

/kind cleanup

Fixes #1107

### CODE REVIEW

File: hack/tools.go [hunk 1]
```diff
@@ -35,9 +35,9 @@ import (
 	_ "knative.dev/pkg/hack"
 
 	// Test images from eventing
+	- "knative.dev/eventing/cmd/heartbeats"
```
Comment (matzew) [inline hack/tools.go:38]: You now need to also run

```
./hack/update-deps.sh --upgrade 
```

**Review by matzew — APPROVED** [review]
/lgtm
/approve
