### PR TITLE
hoist rabbitmqcluster into proper prereq (fix conformance tests)

### LINKED ISSUE #281: Trigger dispatchers do not exit cleanly.
Looks like things are not exiting cleanly. Just jotting this down so we don't forget:
```
t1-cenpmhqu-dispatcher-7445cc894f-qctcw          0/1     CreateContainerConfigError   0          8m10s
t1-ldyylthv-dispatcher-5b977c46fd-ltwng          0/1     CreateContainerConfigError   0          11m
t1-oexecgju-dispatcher-54fcd9d68c-8r8bf          0/1     CrashLoopBackOff             0          72s
t1-ogstraar-dispatcher-54f49d5bbb-wh567          0/1     CrashLoopBackOff             0          4m44s
t1-stgmqson-dispatcher-8c97cc758-mjpvw           0/1     CreateContainerConfigError   0          6m37s
t1-xlsarhmz-dispatcher-7895d7b777-tbtvh          0/1     CreateContainerConfigError   0          10m
trigger-harowruw-dispatcher-6f6f559c7c-8d66b     0/1     CrashLoopBackOff             8          17m
trigger-kqjgoumk-dispatcher-6b8d5dc6d6-676hd     0/1     CrashLoopBackOff             8          17m
trigger-kuxgiowz-dispatcher-5594885888-djk6t     0/1     CrashLoopBackOff             8          17m
trigger-lhxdajgi-dispatcher-6cf4d66c6f-grj8m     0/1     CrashLoopBackOff             8          17m
trigger-ljxmbclt-dispatcher-8465fb4ccc-bmrr8     0/1     CrashLoopBackOff             8          17m
```

So they only seem to happen after something underneath them gets deleted, like so:
```
vaikas@villes-mbp eventing-rabbitmq % kubectl -n test-ejajrvpg logs t1-ogstraar-dispatcher-54f49d5bbb-wh567
{"level":"info","ts":1620152272.595133,"logger":"fallback","caller":"dispatcher/main.go:74","msg":"BackoffDelay is zero, enforcing default","default":0.05}
{"level":"info","ts":1620152272.5953605,"logger":"fallback","caller":"dispatcher/main.go:77","msg":"Setting BackoffDelay","backoffDelay":0.05}
{"level":"info","ts":1620152272.6099005,"logger":"fallback","caller":"dispatcher/dispatcher.go:85","msg":"rabbitmq receiver started, exit with CTRL+C"}
{"level":"info","ts":1620152272.609957,"logger":"fallback","caller":"dispatcher/dispatcher.go:86","msg":"Starting to process messages","queue":"test-ejajrvpg-t1-ogstraar"}
{"level":"warn","ts":1620152284.9375927,"logger":"fallback","caller":"dispatcher/dispatcher.go:96","msg":"message channel closed, stopping message consumer"}
{"level":"warn","ts":1620152284.9379766,"logger":"fallback","caller":"dispatcher/main.go:86","msg":"Failed to close connection: Exception (504) Reason: \"channel/connection is not open\""}
```

### PR DESCRIPTION
**Pull request by vaikas**
# Changes

- :bug: Create one rabbitmqcluster properly in a pre-req. Fixes #281 as well as the conformance tests.
- Prior to this, when we created a broker for a feature we'd also create (and when feature test was done, delete it (bug)) the rabbitmqcluster, so now we create a rabbitmqcluster per namespace (and wait before it goes ready), which will also speed up the tests.
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

File: test/conformance/features/rabbitmqcluster/readyness.go [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+)
+
+// GoesReady returns a feature that will create a RabbitmqCluster
+// and confirm it becomes ready
+func GoesReady(name string, cfg ...manifest.CfgFn) *feature.Feature {
+	f := new(feature.Feature)
+
+	f.Setup(fmt.Sprintf("install rabbitmqcluster %q", name), rabbitmqcluster.Install(name, cfg...))
+
+	f.Requirement("Broker is ready", rabbitmqcluster.IsReady(name))
```
Comment (n3wscott) [inline test/conformance/features/rabbitmqcluster/readyness.go:35]:
```suggestion
	f.Requirement("RabbitmqCluster is ready", rabbitmqcluster.IsReady(name))
```

File: test/conformance/resources/rabbitmqcluster/rabbitmqcluster.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+	"knative.dev/reconciler-test/pkg/feature"
+	"knative.dev/reconciler-test/pkg/k8s"
+	"knative.dev/reconciler-test/pkg/manifest"
+)
+
+func GVR() schema.GroupVersionResource {
+	return schema.GroupVersionResource{Group: "rabbitmq.com", Version: "v1beta1", Resource: "rabbitmqclusters"}
+}
+
+// Install will create a Broker resource, augmented with the config fn options.
```
Comment (n3wscott) [inline test/conformance/resources/rabbitmqcluster/rabbitmqcluster.go:33]:
```suggestion
// Install will create a RabbitmqCluster resource, augmented with the config fn options.
```

**Review by n3wscott — APPROVED** [review]
/lgtm
/approve
