### PR TITLE
Protocol binding refactor

### LINKED ISSUE #939: RabbitMQ source connection retry is not working when no exchange and queue at startup + connection leak + log leak
**Describe the bug**
When rabbitmq does not have exchange and does not have queue, newest rabbitmqsource tries to reconnect, but at the rate that fills up logs very quickly
"Log leak" - there are alot of log messages

### Rabbitmq knative source logs
```
{"level":"error","ts":"2022-10-06T06:56:03.518Z","caller":"adapter/adapter.go:174","msg":"Exception (404) Reason: \"NOT_FOUND - no queue 'my-queue' in vhost '/'\"","commit":"b4d2f33-dirty","stacktrace":"knative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).PollForMessages\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:174\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:113\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).Start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:99\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapterWithContext\n\tknative.dev/eventing@v0.34.1/pkg/adapter/v2/main_message.go:120\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapter\n\tknative.dev/eventing@v0.34.1/pkg/adapter/v2/main_message.go:45\nmain.main\n\tknative.dev/eventing-rabbitmq/cmd/receive_adapter/main.go:26\nruntime.main\n\truntime/proc.go:250"}
{"level":"warn","ts":"2022-10-06T06:56:03.519Z","caller":"rabbit/setup.go:155","msg":"Lost connection to RabbitMQ, reconnecting. Error: %v{error 26 0  Exception (404) Reason: \"NOT_FOUND - no queue 'my-queue' in vhost '/'\"}","commit":"b4d2f33-dirty"}
{"level":"error","ts":"2022-10-06T06:56:03.531Z","caller":"adapter/adapter.go:174","msg":"Exception (404) Reason: \"NOT_FOUND - no queue 'my-queue' in vhost '/'\"","commit":"b4d2f33-dirty","stacktrace":"knative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).PollForMessages\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:174\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:113\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).Start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:99\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapterWithContext\n\tknative.dev/eventing@v0.34.1/pkg/adapter/v2/main_message.go:120\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapter\n\tknative.dev/eventing@v0.34.1/pkg/adapter/v2/main_message.go:45\nmain.main\n\tknative.dev/eventing-rabbitmq/cmd/receive_adapter/main.go:26\nruntime.main\n\truntime/proc.go:250"}
{"level":"warn","ts":"2022-10-06T06:56:03.531Z","caller":"rabbit/setup.go:155","msg":"Lost connection to RabbitMQ, reconnecting. Error: %v{error 26 0  Exception (404) Reason: \"NOT_FOUND - no queue 'my-queue' in vhost '/'\"}","commit":"b4d2f33-dirty"}
{"level":"error","ts":"2022-10-06T06:56:03.538Z","caller":"adapter/adapter.go:174","msg":"Exception (404) Reason: \"NOT_FOUND - no queue 'my-queue' in vhost '/'\"","commit":"b4d2f33-dirty","stacktrace":"knative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).PollForMessages\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:174\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:113\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).Start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:99\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapterWithContext\n\tknative.dev/eventing@v0.34.1/pkg/adapter/v2/main_message.go:120\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapter\n\tknative.dev/eventing@v0.34.1/pkg/adapter/v2/main_message.go:45\nmain.main\n\tknative.dev/eventing-rabbitmq/cmd/receive_adapter/main.go:26\nruntime.main\n\truntime/proc.go:250"}
{"level":"warn","ts":"2022-10-06T06:56:03.539Z","caller":"rabbit/setup.go:155","msg":"Lost connection to RabbitMQ, reconnecting. Error: %v{error 26 0  Exception (404) Reason: \"NOT_FOUND - no queue 'my-queue' in vhost '/'\"}","commit":"b4d2f33-dirty"}
{"level":"error","ts":"2022-10-06T06:56:03.557Z","caller":"adapter/adapter.go:174","msg":"Exception (404) Reason: \"NOT_FOUND - no queue 'my-queue' in vhost '/'\"","commit":"b4d2f33-dirty","stacktrace":"knative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).PollForMessages\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:174\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:113\nknative.dev/eventing-rabbitmq/pkg/adapter.(*Adapter).Start\n\tknative.dev/eventing-rabbitmq/pkg/adapter/adapter.go:99\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapterWithContext\n\tknative.dev/eventing@v0.34.1/pkg/adapter/v2/main_message.go:120\nknative.dev/eventing/pkg/adapter/v2.MainMessageAdapter\n\tknative.dev/eventing@v0.34.1/pkg/adapter/v2/main_message.go:45\nmain.main\n\tknative.dev/eventing-rabbitmq/cmd/receive_adapter/main.go:26\nruntime.main\n\truntime/proc.go:250"}
```
#### Rabbitmq logs
```
2022-10-06 06:56:32.747816+00:00 [info] <0.29836.50> connection <0.29836.50> (10.1.166.17:56058 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
[38;5;160m2022-10-06 06:56:32.787006+00:00 [error] <0.29845.50> Channel error on connection <0.29836.50> (10.1.166.17:56058 -> 10.1.166.47:5672, vhost: '/', user: 'rmquser'), channel 1:[0m
[38;5;160m2022-10-06 06:56:32.787006+00:00 [error] <0.29845.50> operation queue.declare caused a channel exception not_found: no queue 'my-queue' in vhost '/'[0m
2022-10-06 06:56:32.807100+00:00 [info] <0.29851.50> accepting AMQP connection <0.29851.50> (10.1.166.17:56060 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:32.827926+00:00 [info] <0.29851.50> connection <0.29851.50> (10.1.166.17:56060 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
[38;5;160m2022-10-06 06:56:32.846415+00:00 [error] <0.29860.50> Channel error on connection <0.29851.50> (10.1.166.17:56060 -> 10.1.166.47:5672, vhost: '/', user: 'rmquser'), channel 1:[0m
[38;5;160m2022-10-06 06:56:32.846415+00:00 [error] <0.29860.50> operation queue.declare caused a channel exception not_found: no queue 'my-queue' in vhost '/'[0m
2022-10-06 06:56:32.891315+00:00 [info] <0.29864.50> accepting AMQP connection <0.29864.50> (10.1.166.17:56070 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:32.910111+00:00 [info] <0.29864.50> connection <0.29864.50> (10.1.166.17:56070 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
[38;5;160m2022-10-06 06:56:32.913678+00:00 [error] <0.29882.50> Channel error on connection <0.29864.50> (10.1.166.17:56070 -> 10.1.166.47:5672, vhost: '/', user: 'rmquser'), channel 1:[0m
[38;5;160m2022-10-06 06:56:32.913678+00:00 [error] <0.29882.50> operation queue.declare caused a channel exception not_found: no queue 'my-queue' in vhost '/'[0m
```

#### Rabbitmq knative event source logs

```
{"level":"warn","ts":"2022-10-06T06:56:37.715Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.727Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.734Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.745Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.754Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.770Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.780Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.793Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.807Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.827Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.841Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.869Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
{"level":"warn","ts":"2022-10-06T06:56:37.898Z","caller":"adapter/adapter.go:187","msg":"recreating RabbitMQ resources","commit":"b4d2f33-dirty"}
```
#### Rabbitmq logs
```
2022-10-06 06:56:32.917025+00:00 [info] <0.29886.50> accepting AMQP connection <0.29886.50> (10.1.166.17:56076 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:32.922075+00:00 [info] <0.29886.50> connection <0.29886.50> (10.1.166.17:56076 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:32.955752+00:00 [info] <0.29906.50> accepting AMQP connection <0.29906.50> (10.1.166.17:56078 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:32.957966+00:00 [info] <0.29906.50> connection <0.29906.50> (10.1.166.17:56078 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:32.972521+00:00 [info] <0.29918.50> accepting AMQP connection <0.29918.50> (10.1.166.17:56080 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:32.974916+00:00 [info] <0.29918.50> connection <0.29918.50> (10.1.166.17:56080 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:32.987584+00:00 [info] <0.29930.50> accepting AMQP connection <0.29930.50> (10.1.166.17:56082 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:32.991870+00:00 [info] <0.29930.50> connection <0.29930.50> (10.1.166.17:56082 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:33.014265+00:00 [info] <0.29947.50> accepting AMQP connection <0.29947.50> (10.1.166.17:56084 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:33.022254+00:00 [info] <0.29947.50> connection <0.29947.50> (10.1.166.17:56084 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:33.026864+00:00 [info] <0.29958.50> accepting AMQP connection <0.29958.50> (10.1.166.17:56086 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:33.028876+00:00 [info] <0.29958.50> connection <0.29958.50> (10.1.166.17:56086 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:33.038468+00:00 [info] <0.29973.50> accepting AMQP connection <0.29973.50> (10.1.166.17:56088 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:33.040078+00:00 [info] <0.29973.50> connection <0.29973.50> (10.1.166.17:56088 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:33.053219+00:00 [info] <0.29980.50> accepting AMQP connection <0.29980.50> (10.1.166.17:56090 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:33.060891+00:00 [info] <0.29980.50> connection <0.29980.50> (10.1.166.17:56090 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:33.077405+00:00 [info] <0.29999.50> accepting AMQP connection <0.29999.50> (10.1.166.17:56092 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:33.087446+00:00 [info] <0.29999.50> connection <0.29999.50> (10.1.166.17:56092 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
2022-10-06 06:56:33.111576+00:00 [info] <0.30010.50> accepting AMQP connection <0.30010.50> (10.1.166.17:56094 -> 10.1.166.47:5672)[0m
2022-10-06 06:56:33.113902+00:00 [info] <0.30010.50> connection <0.30010.50> (10.1.166.17:56094 -> 10.1.166.47:5672): user 'rmquser' authenticated and granted access to vhost '/'[0m
```
There are a lot of consumers (and count growing) in rabbitmq, probably rabbitmq is overwhelmed by consumers and does not want to accept new connections from other services to publish messages in queue.
image

 **Expected behavior**
There could be some timeout, maybe configurable timeout, where after timeout connection is retried. For example 1 second.

 **To Reproduce**

Set rabbitmq knative source queue config to `predeclared = true`

Motivation to not use `predeclared = false`: 
- in previous rabbitmq knative source versions, when you delete rabbitmq source, queue also is deleted. Thats bad when queue contains data. knativesource needs to be deleted for example when migrating to new knative version which contains immutable fields
- queue and exchange is created with unwanted configuration (headers insted of fanout exchange etc. ...)

```
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: my-source
  namespace: default
spec:
  rabbitmqClusterReference:
    # name: rabbitmq
    namespace: default
    connectionSecret:
      name: rabbitmq
  rabbitmqResourcesConfig:
    predeclared: true
    exchangeName: "my-queue"
    queueName: "my-queue"
    parallelism: 1
  delivery:
    retry: 2592000
    backoffPolicy: "linear"
    backoffDelay: "PT1000S"
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: my-service
      namespace: default
```

 **Knative release version**

Knative - v1.7.3
Knative rabbitmq source - v1.7.1

 **Additional context**
Seems like a priority issue.

### PR DESCRIPTION
**Pull request by gabo1208**
# Changes

- 🧹 Reconnection logic simplified encapsulated and improved in rabbit.connections_handler pkg
- 🧹 Broker Ingress, Dispatcher and Source Adapter reconnection mechanism improved
- 🧹 Predeclared Source does not check Queues nor Exchange config details

/kind enhancement, bug

Fixes #939 #991

### CODE REVIEW

File: pkg/adapter/adapter.go [hunk 1]
```diff
@@ -152,56 +156,38 @@ func (a *Adapter) PollForMessages(stopCh <-chan struct{}) error {
...
-			return
-		case msg, ok := <-msgs:
-			if !ok {
-				return
-			}
-			workerQueue <- msg
-		case <-retryChan:
-			return
+			logger.Error(err)
+			logger.Info("Recreating RabbitMQ Connection and Channel")
```
Comment (gab-satchi) [inline pkg/adapter/adapter.go:188]: can remove the recreating log

File: pkg/adapter/adapter.go [hunk 2]
```diff
@@ -152,56 +156,38 @@ func (a *Adapter) PollForMessages(stopCh <-chan struct{}) error {
...
 		}
+		time.Sleep(time.Second)
```
Comment (gab-satchi) [inline pkg/adapter/adapter.go:190]: just a nit: for readability, this sleep can be inside of the `if err != nil` block. There isn't a non-error case where we'd be sleeping. If it reaches this point, it's because an error happened.

File: pkg/rabbit/connections_handler.go [hunk 3]
```diff
@@ -0,0 +1,247 @@
...
+	retryConnection, retryChannel := true, true
+	for retryConnection || retryChannel {
+		// Wait one cycle duration always except the first time
+		if !r.firstSetup {
+			time.Sleep(time.Millisecond * r.cycleDuration)
+		} else {
+			r.logger.Info("Creating and Configuring RabbitMQ Connection and Channel")
+			r.firstSetup = false
+		}
+		r.Connection, r.Channel, err = r.CreateAndConfigConnectionsAndChannel(&retryConnection, &retryChannel, rabbitMQURL, configFunction, dialFunc)
```
Comment (gab-satchi) [inline pkg/rabbit/connections_handler.go:131]: The way I understand it, the retry booleans save us from recreating a connection when a connection was successful but the channel creation failed. 

It feels overly complex just to save from that one case. It might make more sense to just rely on the `err`. If err happened, call `CloseRabbitMQConnections` just for clean up and then retry after the 1 second wait.

**Review by gab-satchi — COMMENTED** [review]
Mostly nits. I also think the connection setup can be a bit cleaner at the expense of possibly recreating a connection when a channel keeps failing.

File: pkg/rabbit/connections_handler.go [hunk 4]
```diff
@@ -119,23 +118,35 @@ func (r *RabbitMQHelper) SetupRabbitMQConnectionAndChannel(
 	configFunction func(RabbitMQConnectionInterface, RabbitMQChannelInterface) error,
 	dialFunc func(string) (RabbitMQConnectionWrapperInterface, error)) {
 	var err error
-	retryConnection, retryChannel := true, true
-	for retryConnection || retryChannel {
+	for {
 		// Wait one cycle duration always except the first time
 		if !r.firstSetup {
 			time.Sleep(time.Millisecond * r.cycleDuration)
```
Comment (gab-satchi) [inline pkg/rabbit/connections_handler.go:130]: If you move the sleep to L146, can remove the whole `firstSetup` tracking

File: pkg/rabbit/connections_handler.go [hunk 5]
```diff
@@ -119,23 +118,35 @@ func (r *RabbitMQHelper) SetupRabbitMQConnectionAndChannel(
...
 			r.firstSetup = false
 		}
-		r.Connection, r.Channel, err = r.CreateAndConfigConnectionsAndChannel(&retryConnection, &retryChannel, rabbitMQURL, configFunction, dialFunc)
-		if err != nil {
-			r.logger.Error(err)
-			if retryConnection {
-				r.CloseRabbitMQConnections()
-			}
+		// create the connection if needed
+		if r.Connection == nil || r.Connection.IsClosed() {
```
Comment (gab-satchi) [inline pkg/rabbit/connections_handler.go:135]: To keep `SetupRabbitMQConnectionAndChannel` idempotent, we can just call `CloseRabbitMQConnections` at the start of the for loop. That could be the reset to clean up anything leftover.

That function should also set channel to nil as channel is useless without the connection. Also, setting channel to nil is the way to signal to any users of the connection handler that the channel shouldn't be used. So it kind of fits in the "reset" function.

File: pkg/rabbit/connections_handler.go [hunk 6]
```diff
@@ -119,23 +118,35 @@ func (r *RabbitMQHelper) SetupRabbitMQConnectionAndChannel(
...
+		// setup completed successfully
+		if err == nil {
+			break
 		}
+		r.logger.Error(err)
+		r.CloseRabbitMQConnections()
 	}
+	// watch for any connection unexpected closures
 	if r.firstSetup {
 		go r.WatchRabbitMQConnections(ctx, rabbitMQURL, configFunction, dialFunc)
```
Comment (gab-satchi) [inline pkg/rabbit/connections_handler.go:157]: This got me thinking about the `WatchRabbitMQConnections` function. The `firstSetup` is what prevents the watch function from getting called multiple times should `SetupRabbitMQConnectionAndChannel` be called multiple times. `WatchRabbitMQConnections` is in itself public as well so a user can just directly call it multiple times. The function will run indefinitely until the context is cancelled so we definitely don't want more than 1. 

It seems we should have a lock to guarantee only one instance is watching for connection/channel closures.

File: pkg/rabbit/connections_handler.go (hunk 4 above)
Comment (gabo1208) [reply pkg/rabbit/connections_handler.go:130]: No cause in the case that the connection channel and config always succeed (but still somethings goes wrong when starting to use them, for example inspecting for a queue) it can get in an infinite loop of success and no wait

File: pkg/rabbit/connections_handler.go (hunk 5 above)
Comment (gabo1208) [reply pkg/rabbit/connections_handler.go:135]: the thing here is that im trying not to close channels if the connection is alive. So closing everything makes it idempotent but we loose the capability of reconnecting selectively

File: pkg/rabbit/connections_handler.go (hunk 4 above)
Comment (gab-satchi) [reply pkg/rabbit/connections_handler.go:130]: We shouldn't be recreating connections because a failure happened elsewhere with a call to rabbtimq.

Comment (gabo1208) [reply pkg/rabbit/connections_handler.go:130]: In the case of the queue inspect the connection and channel creates fine, but if the queueInspect fails it close the channel (weird design decision but wel...) so its a loop where everything Is working except from the queue and we have to constantly recreate stuff

File: pkg/rabbit/connections_handler.go [hunk 7]
```diff
@@ -0,0 +1,258 @@
...
+	var err error
+	wait := true
+	r.mu.Lock()
+	if r.firstSetup {
+		wait = false
+	}
+	r.mu.Unlock()
+	r.logger.Info("Creating and Configuring RabbitMQ Connection and Channel")
+	for {
+		if wait {
```
Comment (gab-satchi) [inline pkg/rabbit/connections_handler.go:129]: nit: I think we can just use the single firstSetup bool instead of tracking wait separately

File: pkg/rabbit/connections_handler.go [hunk 8]
```diff
@@ -0,0 +1,258 @@
...
+		}
+		// setup completed successfully
+		if err == nil {
+			break
+		}
+		r.logger.Error(err)
+		r.closeRabbitMQConnections()
+	}
+	// watch for any connection unexpected closures
+	r.mu.Lock()
```
Comment (gab-satchi) [inline pkg/rabbit/connections_handler.go:152]: I was expecting the lock in the `watchRabbitMQConnections`. That way the go routine set off to watch for connections and channels will wait if there's already another waiting. With this implementation, it will block any caller to `SetupRabbitMQConnectionAndChannel`

**Review by gab-satchi — APPROVED** [review]
/lgtm
